### ISSUE TITLE
Playing with the naked grammar

### ISSUE THREAD

**Issue by mingodad** [ricomariani/CG-SQL-author#17]
I'm working to achieve a LALR(1)/LEX to try grammars online with wasm based on https://github.com/BenHanson/gram_grep and I've got the `CG-SQL` grammar working, view it here https://mingodad.github.io/parsertl-playground/playground/ select `Cql parser` from the examples, you can edit the Grammar or the Input source and press Parse to see a parser tree.

I hope it can be a nice tool to experiment with LALR(1)/LEX grammars with instant feedback !

**Comment by ricomariani** [comment]
This is cool but I enabled discussions now so you don't have to make an issue to talk to me :D
