### ISSUE TITLE
There should be a builtin cql_throw to throw the value of my choice

### ISSUE THREAD

**Issue by amyworrall** [ricomariani/CG-SQL-author#84]
As mentioned in discussion #83.

Ideally I should be able to pass an enum value into it (even if I have to cast it as an int), so I can have all my possible error conditions in an enum.

**Comment by ricomariani** [comment]
Note that in CQL an enum gives you no advantage over a constant group other than they can be checked for completeness in a switch.  You just want a constant group for your error codes.  You don't want your error codes to change over time so you really want to specify the values.

But in any case you should have no trouble passing enums as error codes.
________________________________
From: amyworrall ***@***.***>
Sent: Friday, February 23, 2024 4:05 PM
To: ricomariani/CG-SQL-author ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ricomariani/CG-SQL-author] There should be a builtin cql_throw to throw the value of my choice (Issue #84)


As mentioned in discussion #83<https://github.com/ricomariani/CG-SQL-author/discussions/83>.

Ideally I should be able to pass an enum value into it (even if I have to cast it as an int), so I can have all my possible error conditions in an enum.

**Comment by ricomariani** [comment]
Done and in Lua too.

**Comment by ricomariani** [comment]
See https://github.com/ricomariani/CG-SQL-author/commit/ec73ec83933fa1845760820b8f82c572030b18ae
