### ISSUE TITLE
Probably a mistake on "sem.c"

### ISSUE THREAD

**Issue by mingodad** [ricomariani/CG-SQL-author#89]
Doing some experiments with this project and passing `-Wextra -Wall` I've noticed the line `sem.c:20728` that seems to be missing the call parameters:

https://github.com/ricomariani/CG-SQL-author/blob/ad1ed28bea2424d0ad915e6c2065313a2417bbf1/sources/sem.c#L20728

**Comment by ricomariani** [comment]
Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Domingo Alvarez Duarte ***@***.***>
Sent: Friday, June 7, 2024 11:42:33 AM
To: ricomariani/CG-SQL-author ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ricomariani/CG-SQL-author] Probably a mistake on "sem.c" (Issue #89)


Doing some experiments with this project and passing -Wextra -Wall I've noticed the line sem.c:20728 that seems to be missing the call parameters:

https://github.com/ricomariani/CG-SQL-author/blob/ad1ed28bea2424d0ad915e6c2065313a2417bbf1/sources/sem.c#L20728

**Comment by ricomariani** [comment]
https://github.com/ricomariani/CG-SQL-author/commit/ee5c245235262456b9b159091cf84cf041c8c38d
