### ISSUE TITLE
Anyone have ported or created an example database for this project ?

### ISSUE THREAD

**Issue by mingodad** [ricomariani/CG-SQL-author#94]
I mean something like the ones in https://dev.mysql.com/doc/index-other.html :
Title	DB Download	HTML Setup Guide	PDF Setup Guide
employee data (large dataset, includes data and test/verification suite)	[GitHub](https://github.com/datacharmer/test_db)	[View](https://dev.mysql.com/doc/employee/en/)	[US Ltr](https://downloads.mysql.com/docs/employee-en.pdf) | [A4](https://downloads.mysql.com/docs/employee-en.a4.pdf)
world database	[TGZ](https://downloads.mysql.com/docs/world-db.tar.gz) | [Zip](https://downloads.mysql.com/docs/world-db.zip)	[View](https://dev.mysql.com/doc/world-setup/en/)	[US Ltr](https://downloads.mysql.com/docs/world-setup-en.pdf) | [A4](https://downloads.mysql.com/docs/world-setup-en.a4.pdf)
sakila database	[TGZ](https://downloads.mysql.com/docs/sakila-db.tar.gz) | [Zip](https://downloads.mysql.com/docs/sakila-db.zip)	[View](https://dev.mysql.com/doc/sakila/en/)	[US Ltr](https://downloads.mysql.com/docs/sakila-en.pdf) | [A4](https://downloads.mysql.com/docs/sakila-en.a4.pdf)
airportdb database (large dataset, intended for MySQL on OCI and HeatWave)	[TGZ](https://downloads.mysql.com/docs/airport-db.tar.gz) | [Zip](https://downloads.mysql.com/docs/airport-db.zip)	[View](https://dev.mysql.com/doc/airportdb/en/)	[US Ltr](https://downloads.mysql.com/docs/airportdb-en.pdf) | [A4](https://downloads.mysql.com/docs/airportdb-en.a4.pdf)
menagerie database	[TGZ](https://downloads.mysql.com/docs/menagerie-db.tar.gz) | [Zip](https://downloads.mysql.com/docs/menagerie-db.zip)

**Comment by ricomariani** [comment]
I made discussion boards for discussions but nobody uses them.  I once ported the northwinds database for SQL server that was  pretty easy.  Any sqlite sample will work pretty much.  You can connect to it and use `.schema` for the declarations if it has normal column names.  You might have to change to the `column` syntax if it has weird names.  I've done this for hundreds of databases.  But I don't have rights to those so I can't share.

**Comment by mingodad** [comment]
Thank you for reply !

**Comment by mingodad** [comment]
There is a way to convert this issue to discussion ?

**Comment by mingodad** [comment]
After you've mentioned the northwind database conversion I found this https://en.wikiversity.org/wiki/Database_Examples/Northwind/SQLite to use as base and one thing that came out is taht G-SQL``doesn't have `DATE/DATETIME` types.

Can you share your port ?

**Comment by mingodad** [comment]
And also this https://github.com/jOOQ/sakila

**Comment by mingodad** [comment]
From the `sakyla` database:
```
create proc go()
begin
CREATE TABLE actor (
  actor_id INTEGER NOT NULL ,
  first_name TEXT NOT NULL, --VARCHAR(45) NOT NULL,
  last_name TEXT NOT NULL, --VARCHAR(45) NOT NULL,
  last_update TEXT<TIMESTAMP> NOT NULL,
  PRIMARY KEY  (actor_id)
  )
  ;

CREATE  INDEX idx_actor_last_name ON actor(last_name)
;

CREATE TRIGGER actor_trigger_ai AFTER INSERT ON actor
 BEGIN
  UPDATE actor SET last_update = DATETIME('NOW')  WHERE rowid = new.rowid;
 END
;

CREATE TRIGGER actor_trigger_au AFTER UPDATE ON actor
 BEGIN
  UPDATE actor SET last_update = DATETIME('NOW')  WHERE rowid = new.rowid;
 END
;
end;
```
Output:
```
code.cql:17:1: error: in call : CQL0013: cannot assign/copy possibly null expression to not null target 'last_update'
code.cql:23:1: error: in call : CQL0013: cannot assign/copy possibly null expression to not null target 'last_update'
semantic errors present; no code gen.
```

**Comment by mingodad** [comment]
Again from the `sakyla` database:
```
create proc go()
begin
CREATE TABLE country (
  country_id INTEGER NOT NULL,
  country TEXT NOT NULL, --VARCHAR(50)
  last_update TEXT<TIMESTAMP>,
  PRIMARY KEY  (country_id)
)
;

CREATE TRIGGER country_trigger_ai AFTER INSERT ON country
 BEGIN
  UPDATE country SET last_update = DATETIME('NOW')  WHERE rowid = new.rowid;
 END
;

CREATE TRIGGER country_trigger_au AFTER UPDATE ON country
 BEGIN
  UPDATE country SET last_update = DATETIME('NOW')  WHERE rowid = new.rowid;
 END
;
end;
```
Output:
```
code.cql:13:1: error: in dot : CQL0069: name not found 'new.rowid'
code.cql:19:1: error: in dot : CQL0069: name not found 'new.rowid'
semantic errors present; no code gen.
```

**Comment by mingodad** [comment]
Testing both of the above examples on https://mingodad.github.io/parsertl-playground/playground/ generates a parser tree so the parser is fine but after it it's failing

**Comment by mingodad** [comment]
Also mutually referencing tables foreign key is parsed fine but rejected:
```
create proc go()
begin
--
-- Table structure for table store
--

CREATE TABLE store (
  store_id INTEGER NOT NULL,
  manager_staff_id INT NOT NULL,
  address_id INT NOT NULL,
  last_update TEXT<TIMESTAMP> NOT NULL,
  PRIMARY KEY  (store_id),
  CONSTRAINT fk_store_staff FOREIGN KEY (manager_staff_id) REFERENCES staff (staff_id) ,
  CONSTRAINT fk_store_address FOREIGN KEY (address_id) REFERENCES address (address_id)
)
;

CREATE  INDEX idx_store_fk_manager_staff_id ON store(manager_staff_id)
;

CREATE  INDEX idx_fk_store_address ON store(address_id)
;

CREATE TRIGGER store_trigger_ai AFTER INSERT ON store
 BEGIN
  UPDATE store SET last_update = DATETIME('NOW')  WHERE rowid = new.rowid;
 END
;

CREATE TRIGGER store_trigger_au AFTER UPDATE ON store
 BEGIN
  UPDATE store SET last_update = DATETIME('NOW')  WHERE rowid = new.rowid;
 END
;

--
-- Table structure for table staff
--

CREATE TABLE staff (
  staff_id INTEGER NOT NULL,
  first_name TEXT NOT NULL, --VARCHAR(45)
  last_name TEXT NOT NULL, --VARCHAR(45)
  address_id INT NOT NULL,
  picture BLOB,
  email TEXT, --VARCHAR(50)
  store_id INT NOT NULL,
  active SMALLINT DEFAULT 1 NOT NULL,
  username TEXT NOT NULL, --VARCHAR(16)
  password TEXT, --VARCHAR(40)
  last_update TEXT<TIMESTAMP> NOT NULL,
  PRIMARY KEY  (staff_id),
  CONSTRAINT fk_staff_store FOREIGN KEY (store_id) REFERENCES store (store_id) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT fk_staff_address FOREIGN KEY (address_id) REFERENCES address (address_id) ON DELETE NO ACTION ON UPDATE CASCADE
)
;
CREATE  INDEX idx_fk_staff_store_id ON staff(store_id)
;

CREATE  INDEX idx_fk_staff_address_id ON staff(address_id)
;

CREATE TRIGGER staff_trigger_ai AFTER INSERT ON staff
 BEGIN
  UPDATE staff SET last_update = DATETIME('NOW')  WHERE rowid = new.rowid;
 END
;

CREATE TRIGGER staff_trigger_au AFTER UPDATE ON staff
 BEGIN
  UPDATE staff SET last_update = DATETIME('NOW')  WHERE rowid = new.rowid;
 END
;

end;
```
Output:
```
code.cql:13:1: error: in fk_def : CQL0021: foreign key refers to non-existent table 'staff'
code.cql:18:1: error: in str : CQL0019: create index table name not found 'store'
code.cql:21:1: error: in str : CQL0019: create index table name not found 'store'
code.cql:24:1: error: in str : CQL0137: table/view not found 'store'
code.cql:30:1: error: in str : CQL0137: table/view not found 'store'
code.cql:48:1: error: in col_def_type_attrs : CQL0360: unknown type 'SMALLINT'
code.cql:57:1: error: in str : CQL0019: create index table name not found 'staff'
code.cql:60:1: error: in str : CQL0019: create index table name not found 'staff'
code.cql:63:1: error: in str : CQL0137: table/view not found 'staff'
code.cql:69:1: error: in str : CQL0137: table/view not found 'staff'
semantic errors present; no code gen.
```

**Comment by ricomariani** [comment]
CQL strongly requires a total ordering of tables that works, so cycles in foreign keys are just never going to be supported.

The issue with new.rowid not resolving is fixed in https://github.com/ricomariani/CG-SQL-author/commit/4bb32c4e5071d77e3f69abf81c9eeddceb2a8b71
